Inventario/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from inventario_app.views import inventario_app, administrador, soporte, laboratorio

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('inventario_app.urls')),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', inventario_app.SignUpView.as_view(), name='signup'),
    path('accounts/signup/administrador/', administrador.AdministradorSignUpView.as_view(), name='administrador_signup'),
    path('accounts/signup/laboratorio/', laboratorio.LaboratorioSignUpView.as_view(), name='laboratorio_signup'),
    path('accounts/signup/soporte/', soporte.SoporteSignUpView.as_view(), name='soporte_signup'),


    


]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inventario_app/urls.py
from django.urls import include, path
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static

from .views import inventario_app, administrador, soporte, laboratorio

urlpatterns = [
    path('', inventario_app.home, name='home'),

    path('administrador/', include(([
        path('', administrador.index, name='index'),
        path('despacho/<int:pk>/reporte_todos_excel/',administrador.ReporteTodosExcel.as_view(), name="reporte_todos_excel"),
        path('insumo/BCAM', administrador.insumo_list, name='BCAM'),
        path('insumo/index', administrador.insumo_index, name='insumo_index'),
        path('insumo/CSAB/', administrador.baluarte, name='CSAB'),
        path('insumo/BCM/', administrador.bc_maipu, name='BCM'),
        path('insumo/BCLF/',administrador.bc_farfana, name='BCLF'),
        path('insumo/CEB/',administrador.el_bosque, name='CEB'),
        path('insumo/CICV/',administrador.inmaculada_vitacura, name='CICV'),
        path('insumo/CLA/',administrador.los_alpes, name='CLA'),
        path('insumo/CMAN/',administrador.manantial, name='CMAN'),
        path('insumo/CSE/',administrador.sebastian_alcano, name='CSE'),
        path('insumo/CSFP/',administrador.san_francisco, name='CSFP'),
        path('insumo/CSM/',administrador.san_marcos, name='CSM'),
        path('insumo/IOM/',administrador.iom, name='IOM'),
        path('insumo/SSLA/',administrador.san_sebastia, name='SSLA'),
        path('insumo/add/', administrador.crear_insumo, name='insumo_form'),
        path('actividad/', administrador.actividad, name='actividad'),
        path('reportes/', administrador.reportes, name='reportes'),
        path('reportes/add/', administrador.crear_reporte, name='reporte_add'),
        path('reportes/<int:pk>/reportes_new/add/', administrador.crear_reporte_new, name='reporte_new_add'),
        path('reportes/<int:pk>', administrador.reportes_view, name='reportes_view'),
        path('inventario/<int:pk>/despacho/add/', administrador.crear_despacho, name='despacho'),
        path('despacho/', administrador.despacho, name='despacho_list'),
        path('despacho/<int:pk>', administrador.despacho_detail, name='despacho_detail'),
        path('usuarios/', administrador.usuarios, name='usuarios'),
        path('inventario/add/', administrador.crear_inventario, name='inventario_add'),
        path('inventario/<int:pk>/update', administrador.change_inventario, name='editar_inventario'),
        path('inventario/<int:pk>/delete/', administrador.InventarioDeleteView.as_view(), name='inventario_delete'),
        path('inventario/<int:pk>', administrador.descripcion, name='inventario_detalle'),
        path('inventario/<int:pk>/adicional/add/', administrador.crear_adicional, name='adicional_add'),
        path('inventario/<int:inventario_pk>/adicional/<int:adicional_pk>/', administrador.adicional_change, name='adicional_edit'),
        path('inventario/<int:pk>/monitor/add/', administrador.crear_monitor, name='monitor_add'),
        path('inventario/<int:inventario_pk>/monitor/<int:monitor_pk>/', administrador.monitor_change, name='monitor_edit'),
        path('inventario/<int:inventario_pk>/monitor/<int:monitor_pk>/delete/', administrador.MonitorDeleteView.as_view(), name='monitor_delete'),
        path('inventario/<int:pk>/incidencia/add/', administrador.crear_incidencia, name='incidencia_add'),


    ], 'inventario_app'), namespace='administrador')),

    path('soporte/', include(([
        path('', soporte.index, name='index'),
        path('reportes/', soporte.reportes, name='reportes'),
        path('reportes/add/', soporte.crear_reporte, name='reporte_add'),
        path('reportes/<int:pk>/reportes_new/add/', soporte.crear_reporte_new, name='reporte_new_add'),
        path('reportes/<int:pk>', soporte.reportes_view, name='reportes_view'),
        path('inventario/add/', soporte.CrearInventarioView.as_view(), name='inventario_add'),
        path('inventario/<int:pk>', soporte.descripcion, name='inventario_detalle'),
        path('inventario/<int:pk>/adicional/add/', soporte.crear_adicional, name='adicional_add'),
        path('inventario/<int:pk>/monitor/add/', soporte.crear_monitor, name='monitor_add'),
        path('inventario/<int:pk>/incidencia/add/', soporte.crear_incidencia, name='incidencia_add'),        
    ], 'inventario_app'), namespace='soporte')),
    
    path('laboratorio/', include(([
        path('', laboratorio.index, name='index'),
        path('reportes/', laboratorio.reportes, name='reportes'),
        path('reportes/add/', laboratorio.crear_reporte, name='reporte_add'),
        path('reportes/<int:pk>/reportes_new/add/', laboratorio.crear_reporte_new, name='reporte_new_add'),
        path('reportes/<int:pk>', laboratorio.reportes_view, name='reportes_view'),
        path('inventario/add/', laboratorio.CrearInventarioView.as_view(), name='inventario_add'),
        path('inventario/<int:pk>', laboratorio.descripcion, name='inventario_detalle'),
        path('inventario/<int:pk>/adicional/add/', laboratorio.crear_adicional, name='adicional_add'),
        path('inventario/<int:pk>/monitor/add/', laboratorio.crear_monitor, name='monitor_add'),
        path('inventario/<int:pk>/incidencia/add/', laboratorio.crear_incidencia, name='incidencia_add'),
    ], 'inventario_app'), namespace='laboratorio')),
    


]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inventario_app/views/administrador.py
import json
import traceback
from itertools import chain
from .__init__ import *
from django.contrib.admin.models import LogEntry, ADDITION, CHANGE
from django.contrib.contenttypes.models import ContentType
from openpyxl import Workbook
from openpyxl.styles import Alignment, Border, PatternFill, Font, Side
from openpyxl.drawing.image import Image
from django.core.mail import EmailMessage, EmailMultiAlternatives
from django.template.loader import get_template,render_to_string
from django.utils.html import strip_tags
from django.template import Context
from django.contrib import messages
from django.contrib.auth import login
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Avg, Count, Sum, Min, Max, Func
from django.contrib.auth.models import User
from django.forms import inlineformset_factory, modelformset_factory
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.http import JsonResponse,HttpResponse, HttpResponseRedirect, HttpRequest
from django.views.generic import (TemplateView,CreateView, DeleteView, DetailView, ListView,
                                  UpdateView, TemplateView, View)
from ..decorators import administrador_required
from datetime import date, datetime                                  
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse
from rest_framework.views import APIView
from rest_framework.response import Response
from inventario_app.forms import AdministradorSignUpForm, InsumoForm,CrearInventarioForm,EditarInventarioForm ,CrearCaracteristicasForm, CrearMonitorForm, IncidenciaForm, ReporteForm, ReporteNewForm,DespachoForm
from inventario_app.models import Inventario, Marca, User, Equipo, Administrador, Colegios, Adicional, Monitor, Incidencia, Reporte, ReporteNew, Despacho, Images, Insumoform, Insumos

# Create your views here.
class ReporteTodosExcel(TemplateView):
     
    #Usamos el método get para generar el archivo excel 
    def get(self, request, pk,*args, **kwargs):
        #Obtenemos todas las personas de nuestra base de datos
        personas = Despacho.objects.filter(pk=pk)
        #Creamos el libro de trabajo
        wb = Workbook()
        #Definimos como nuestra hoja de trabajo, la hoja activa, por defecto la primera del libro
        ws = wb.active
        llenar = PatternFill(start_color = 'FFFFFF', end_color='FFFFFF', fill_type="solid")
        borde = Border(left = Side(border_style = "none"), right= Side(border_style= "none"),
                                top= Side(border_style = "none"), bottom= Side(border_style= "none"))
        thin = Border(bottom=Side(border_style='medium'))
        medium = Border(left = Side(border_style = "medium"), right= Side(border_style= "medium"),
                                top= Side(border_style = "medium"), bottom= Side(border_style= "medium"))
        mediumii = Border(left = Side(border_style = "medium"), right= Side(border_style= "medium"),
                                 bottom= Side(border_style= "medium"))
        lado = Border(left = Side(border_style = "medium"), right= Side(border_style= "medium"))
        inferior = Border( bottom= Side(border_style= "medium"))

        img = Image('static/img/logo_2.jpg')
        #En la celda B1 ponemos el texto 'REPORTE DE PERSONAS'
        ws['C5'] = 'FICHA DE ENTREGA DE EQUIPAMIENTO'
        ws['C5'].font = Font(name='Calibri', size=24, bold=True)
        ws['C5'].alignment = Alignment(indent=2 )

        #Juntamos las celdas desde la B1 hasta la E1, formando una sola celda
        ws.merge_cells('C5:H5')
        ws.merge_cells('G6:H6')
        ws.add_image(img, 'A1')

        ws['A1'].border = borde
        ws['A2'].border = borde
        ws['A3'].border = borde
        ws['A4'].border = borde
        ws['A5'].border = borde
        ws['A6'].border = borde
        ws['A7'].border = borde
        ws['A8'].border = borde
        ws['A9'].border = borde
        ws['A10'].border = borde
        ws['A11'].border = medium
        ws['A12'].border = lado
        ws['A13'].border = mediumii
        ws['A14'].border = borde
        ws['A15'].border = borde
        ws['A16'].border = medium
        ws['A17'].border = medium
        ws['A18'].border = borde
        ws['A19'].border = borde
        ws['A20'].border = borde
        ws['A21'].border = borde
        ws['A22'].border = borde
        ws['A23'].border = borde
        ws['A24'].border = borde
        ws['A25'].border = borde
        ws['A26'].border = borde
        ws['A27'].border = borde
        ws['A28'].border = borde
        ws['A29'].border = borde
        ws['A30'].border = borde
        ws['A31'].border = borde
        ws['A32'].border = borde
        ws['A33'].border = borde
        ws['A34'].border = borde
        ws['A35'].border = borde
        ws['A36'].border = borde
        ws['A1'].fill = llenar
        ws['A2'].fill = llenar
        ws['A3'].fill = llenar
        ws['A4'].fill = llenar
        ws['A5'].fill = llenar
        ws['A6'].fill = llenar
        ws['A7'].fill = llenar
        ws['A8'].fill = llenar
        ws['A9'].fill = llenar
        ws['A10'].fill = llenar
        ws['A11'].fill = llenar
        ws['A12'].fill = llenar
        ws['A13'].fill = llenar
        ws['A14'].fill = llenar
        ws['A15'].fill = llenar
        ws['A16'].fill = llenar
        ws['A17'].fill = llenar
        ws['A18'].fill = llenar
        ws['A19'].fill = llenar
        ws['A20'].fill = llenar
        ws['A21'].fill = llenar
        ws['A22'].fill = llenar
        ws['A23'].fill = llenar
        ws['A24'].fill = llenar
        ws['A25'].fill = llenar
        ws['A26'].fill = llenar
        ws['A27'].fill = llenar
        ws['A28'].fill = llenar
        ws['A29'].fill = llenar
        ws['A30'].fill = llenar
        ws['A31'].fill = llenar
        ws['A32'].fill = llenar
        ws['A33'].fill = llenar
        ws['A34'].fill = llenar
        ws['A35'].fill = llenar
        ws['A36'].fill = llenar

        ws['B1'].border = borde
        ws['B2'].border = borde
        ws['B3'].border = borde
        ws['B4'].border = borde
        ws['B5'].border = borde
        ws['B6'].border = borde
        ws['B7'].border = borde
        ws['B8'].border = borde
        ws['B9'].border = borde
        ws['B10'].border = borde
        ws['B11'].border = borde
        ws['B12'].border = lado
        ws['B13'].border = mediumii
        ws['B14'].border = borde
        ws['B15'].border = borde
        ws['B16'].border = medium
        ws['B17'].border = medium
        ws['B18'].border = borde
        ws['B19'].border = borde
        ws['B20'].border = borde
        ws['B21'].border = borde
        ws['B22'].border = borde
        ws['B23'].border = borde
        ws['B24'].border = borde
        ws['B25'].border = borde
        ws['B26'].border = borde
        ws['B27'].border = borde
        ws['B28'].border = borde
        ws['B29'].border = borde
        ws['B30'].border = borde
        ws['B31'].border = borde
        ws['B32'].border = borde
        ws['B33'].border = borde
        ws['B34'].border = borde
        ws['B35'].border = borde
        ws['B36'].border = borde
        ws['B1'].fill = llenar
        ws['B2'].fill = llenar
        ws['B3'].fill = llenar
        ws['B4'].fill = llenar
        ws['B5'].fill = llenar
        ws['B6'].fill = llenar
        ws['B7'].fill = llenar
        ws['B8'].fill = llenar
        ws['B9'].fill = llenar
        ws['B10'].fill = llenar
        ws['B11'].fill = llenar
        ws['B12'].fill = llenar
        ws['B13'].fill = llenar
        ws['B14'].fill = llenar
        ws['B15'].fill = llenar
        ws['B16'].fill = llenar
        ws['B17'].fill = llenar
        ws['B18'].fill = llenar
        ws['B19'].fill = llenar
        ws['B20'].fill = llenar
        ws['B21'].fill = llenar
        ws['B22'].fill = llenar
        ws['B23'].fill = llenar
        ws['B24'].fill = llenar
        ws['B25'].fill = llenar
        ws['B26'].fill = llenar
        ws['B27'].fill = llenar
        ws['B28'].fill = llenar
        ws['B29'].fill = llenar
        ws['B30'].fill = llenar
        ws['B31'].fill = llenar
        ws['B32'].fill = llenar
        ws['B33'].fill = llenar
        ws['B34'].fill = llenar
        ws['B35'].fill = llenar
        ws['B36'].fill = llenar

        ws['C2'].border = borde
        ws['C1'].border = borde
        ws['C3'].border = borde
        ws['C4'].border = borde
        ws['C5'].border = borde
        ws['C6'].border = thin
        ws['C7'].border = thin
        ws['C8'].border = thin
        ws['C9'].border = borde
        ws['C10'].border = borde
        ws['C11'].border = medium
        ws['C12'].border = lado
        ws['C13'].border = mediumii
        ws['C14'].border = borde
        ws['C15'].border = borde
        ws['C16'].border = medium
        ws['C17'].border = medium
        ws['C18'].border = borde
        ws['C19'].border = borde
        ws['C20'].border = borde
        ws['C21'].border = borde
        ws['C22'].border = borde
        ws['C23'].border = borde
        ws['C24'].border = borde
        ws['C25'].border = borde
        ws['C26'].border = borde
        ws['C27'].border = borde
        ws['C28'].border = borde
        ws['C29'].border = borde
        ws['C30'].border = borde
        ws['C31'].border = borde
        ws['C32'].border = borde
        ws['C33'].border = borde
        ws['C34'].border = borde
        ws['C35'].border = borde
        ws['C36'].border = borde
        ws['C1'].fill = llenar

inventario_app/templates/inventario_app/administrador/despacho/crear_despacho.html
{% extends 'inventario_app/administrador/despacho/heder.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
            
            <h1 class="h3">Crear Despacho</h1>
            <br>
            <div class="container" style="align-content: center;">
                  <div class="row">
                    <div class="col-md-8 col-sm-10 col-12">
                      <form method="post" enctype="multipart/form-data", novalidate>
                        {% csrf_token %}
                        <div class="row">
                          <div class="col-4">
                            {{ form.usuario|as_crispy_field }}
                          </div>
                          <div class="col-4">
                            {{ form.area|as_crispy_field }}
                          </div>
                          <div class="col-4">
                            {{ form.solicitado|as_crispy_field }}
                          </div>
                          <div class="col-4">
                            {{ form.fecha_entrega|as_crispy_field }}
                          </div>
                          <div class="col-4">
                            {{ form.destino|as_crispy_field }}
                          </div>
                          <div class="col-6">
                            {{ form.extras|as_crispy_field }}
                          </div>
                        </div>
                        <button type="submit" class="btn btn-success">Agregar</button>
                        <a href="{% url 'administrador:despacho_list' %}" class="btn btn-danger">Cancelar</a>

                      </form>
                      <br>
                    </div>
                  </div>
              </div>
            
          {% endblock %}  

inventario_app/templates/inventario_app/administrador/despacho/despacho_detail.html
{% extends 'inventario_app/administrador/despacho/heder.html' %}

{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<a href="{% url 'administrador:reporte_todos_excel' despacho.pk %}">Imprimir</a>
            {% if despacho.destino.imagen  %}
            <div class="img-fluid ">

                <img src=" {{despacho.destino.imagen.url}} " style="margin-left: 250px;" alt="">
            {% endif %}
            </div>
            <br>

            <p style="margin-left: 250px;"> <strong>FICHA DE ENTREGA DE EQUIPAMIENTO</strong> </p>

            <div class="row ">
                <div class="col-4">
                  <strong>Usuario: </strong> <ins> {{despacho.usuario}} </ins>
                </div>
                <div class="col-6" >
                  <strong>Solicitado</strong> <ins>{{despacho.solicitado}}</ins> 
                </div>
                <div class="col-4">
                  <strong>Área:</strong> <ins>{{despacho.area}}</ins> 
                </div>
                <div class="col-6">
                  <strong>Fecha de entrega</strong> <ins> {{despacho.fecha_entrega|date:"d/m/Y"}}</ins>
                </div>
                <div class="col-4">
                  <strong>Origen:</strong> <ins>{{despacho.origen}}</ins> 
                </div>


                <div class="col-4" >
                    <strong>Destino:</strong> <ins>{{despacho.destino}}</ins> 
                </div>


                <br>
                <br>
            </div>

                <div class="table-responsive">
                <table id="example" class="table table-striped display table-sm">
                    <thead>
                        <tr>
                          <th>Id</th>
                          <th>Colegio</th>
                          <th>Equipo</th>
                          <th>Marca</th>
                          <th>Modelo</th>
                          <th>Serie</th>
                          <th>Código</th>
                          <th>Condición</th>
      
                        </tr>
                    </thead>
                    <tbody>
                    <tr style="text-transform: uppercase;">
                        <td>{{despacho.equipo.id}}</td>
                        <td>{{despacho.equipo.colegio}}</td>
                        <td>{{despacho.equipo.equipo}}</td>
                        <td>{{despacho.equipo.marca}}</td>
                        <td>{{despacho.equipo.modelo}}</td>
                        <td>{{despacho.equipo.serie}}</td>
                        <td>{{despacho.equipo.codigo}}</td>
                        <td>{{despacho.equipo.condicion}}</td>

                    </tr>

                    </tbody>
                </table>
            </div>
            <div class="table-responsive">
                  <table class="table table-striped table-sm">
                    <thead>
                      <tr>
                        <th>Procesador</th>
                        <th>Ram</th>
                        <th>Sistema</th>
                        <th>Disco</th>
                        <th>Placa Madre</th>
                        <th>Office</th>    
                      </tr>
                    </thead>
                    <tbody>
                        {% for inventarios in despacho.equipo.inventarios.all %}
                        <tr>
                        <td>{{inventarios.procesador}}</td>
                        <td>{{inventarios.ram}}</td>
                        <td>{{inventarios.sistema}}</td>
                        <td>{{inventarios.disco}}</td>
                        <td>{{inventarios.placa}}</td>
                        <td>{{inventarios.office}}</td>
                      </tr>
                      {% empty %}
                      <tr>
                        <td class="bg-light text-center font-italic" colspan="5">No tiene caracteristicas todavia</td>
                      </tr>
                    {% endfor %}
                    </tbody>
                  </table>
              </div>
              <div class="container-fluid">
                <ul>
                    {% for extras in despacho.extras.all %}
                    <li> {{extras.name}} </li>
                    {% endfor %}
                </ul>


            </div>
            <ins style=" text-align: center; "> <p style="color: white;"> bbbbbbbbbbbbbbbbbbbbblablablabla</p> </ins>
            <p style="text-align: center; text-transform: uppercase;"> <strong>Firma recibido conforme</strong>  </p>
          
            {% endblock %}

inventario_app/templates/inventario_app/administrador/despacho/despacho_list.html
{% extends 'inventario_app/administrador/despacho/heder.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block content %}           
            <br>

            <div class="table-responsive">
              <table id="example" class="table table-striped display table-sm">
                <thead>
                  <tr>
                    <th>Id</th>
                    <th>Tipo</th>
                    <th>Origen</th>
                    <th>Equipo</th>
                    <th>Destino</th>
                    <th></th>

                  </tr>
                </thead>
                <tbody>
                  {% for despacho in despacho %}
                  <tr>
                    <td>{{despacho.id}}</td>
                    <td> {{despacho.equipo.equipo}} </td>
                    <td>{{despacho.origen}}</td>
                    <td style="text-transform: uppercase;">{{despacho.equipo.codigo}}</td>
                    <td>{{despacho.destino}}</td>

                    <td class="text-right">
                      <a href="{% url  'administrador:despacho_detail' despacho.pk %}" class="btn btn-primary">Ver</a>
                    </td>
                  </tr>
                  {% empty %}
                  <tr>
                    <td class="bg-light text-center font-italic" colspan="5">No tienes creado ningun inventario todavia</td>
                  </tr>
                {% endfor %}
                </tbody>
              </table>
            </div>
{% endblock %}         

inventario_app/templates/inventario_app/administrador/despacho/heder.html
{% load static %}
{% load crispy_forms_tags %}
{% if user.is_authenticated and user.is_administrador %}
<!DOCTYPE html> 
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/css?family=Clicker+Script" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">    <link rel="stylesheet" type="text/css" href="{% static "vendor/fontello-2f186091/css/fontello.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "css/animations.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "css/administrador.css" %}">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">


    <title>Administrador</title>
    <meta name="theme-color" content="#563d7c">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
</head>
<body>
  <nav class="navbar  fixed-top  flex-md-nowrap p-0 " style="background-color: #0D32B1;">
    <a class="navbar-brand col-sm-3 col-md-2 mr-0" href='/' style="color: white;">Departamento Informática</a>
    <ul class="navbar-nav px-3">
      <li class="nav-item text-nowrap">
        <a class="nav-link" href="{% url 'logout' %}" style="color: white;">Salir</a>
      </li>
    </ul>
  </nav>
      <div class="container-fluid">
        <div class="row">
            <nav class="col-md-2 d-none d-md-block bg-light sidebar">
              <img    src="{% static "img/logo.jpg" %}"  class="img-thumbnail" style="width:230px;height:70px;"  alt="">

                <div class="sidebar-sticky">
                  <ul class="nav flex-column">
                    <li class="nav-item">
                      <a class="nav-link " href="/">
                        <i class="fas fa-table"></i>
                        Inventario 
                      </a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'administrador:actividad' %}">
                        <i class="fas fa-clipboard-list"></i>
                        Actividad
                      </a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'administrador:reportes' %}">
                        <i class="far fa-file-alt"></i>
                        Reportes Diarios
                      </a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'administrador:usuarios' %}">
                        <i class="fas fa-users"></i>                   
                        Usuarios
                      </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'administrador:despacho_list' %}">
                            <i class="fas fa-dolly"></i>   
                            Movimientos
                        </a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link " href="{%url 'administrador:insumo_index' %}">
                        <i class="fas fa-desktop"></i>
                          Insumos
                      </a>
                  </li>         
                  </ul>
          
                  <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                
                    <span> <strong>Usuario:</strong> {{user.username}}</span>
                    <a class="d-flex align-items-center text-muted" href="#" aria-label="Add a new report">
                      <span data-feather="plus-circle"></span>
                    </a>
                  </h6>
                </div>
              </nav>
      
          <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
            {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
                  {{ message }}
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
              {% endfor %}
            <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
              <h1 class="h2">Movimientos</h1>
            </div>
            
            {% block content %}
            
            {% endblock %}
          </main>
        </div>
      </div>
{% endif %}
</body>

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="{% static "js/jquery.plugin.min.js" %}"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.bundle.js" integrity="sha256-o8aByMEvaNTcBsw94EfRLbBrJBI+c3mjna/j4LrfyJ8=" crossorigin="anonymous"></script>    

</html>